title: "[Idea]: "
labels: ["enhancement", "discussion"]
body: |
  ## What's your idea?

  <!-- Describe your feature idea or improvement suggestion -->

  ## Why would this be valuable?

  <!-- Explain the problem this solves or the value it adds -->

  ## How would it work?

  <!-- Describe how you envision this feature working -->

  ## Who would benefit?

  <!-- Which users or use cases would this help? -->

  ## Alternatives you've considered

  <!-- Any other approaches or solutions you've thought about -->

  ## Additional context

  <!-- Any examples, mockups, or references that might help -->
