blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/artem-schander/protest-scraper/discussions
    about: Ask questions or discuss ideas with the community
  - name: Security Issue
    url: mailto:schander.artem@gmail.com
    about: Report security vulnerabilities privately (do not create public issues)
